/**
 * Takes — every attempt at a shot, including the ones that failed.
 *
 * A scene in this world is not filmed once. Each beat is generated over and
 * over until one of them is right, and the rest are thrown away. This is where
 * the rest go: the near misses, the ones where a hand lands wrong, and the
 * genuinely horrible ones. Members can watch all of them next to the finished
 * scene, which is the only honest way to show that the good frames were
 * *chosen* rather than found.
 *
 * WHY IT IS SHAPED THIS WAY. A flat wall of four hundred clips is a file
 * server, not an experience. What tells the story is the RUN — fourteen
 * attempts at the same moment, in the order they were made, with the one that
 * made the final cut marked. Ordering plus a star does all the narrative work,
 * with no commentary to write, which is what keeps adding a scene's takes a
 * matter of dropping files in a folder.
 *
 * ALWAYS MEMBERS-ONLY (`TAKES_ACCESS`). Not a per-take field, because there is
 * no version of this that is partly public: the failures are the most
 * openly-AI artefacts in the product, and CLAUDE.md puts production method in
 * behind-the-scenes material rather than out front of the story. Behind the
 * membership is exactly where that lands.
 *
 * NOT HAND-WRITTEN. Everything under lib/content/takes-data/ is generated by
 * scripts/import-takes.sh from the folder layout described there. Edit the
 * folders and re-run it; edits made here are overwritten.
 */

import type { AccessLevel } from "@/lib/content/videos";

import { lunaCathyPhoneTakes } from "@/lib/content/takes-data/luna-cathy-phone";
import { tysonColeBarTakes } from "@/lib/content/takes-data/tyson-cole-bar";

/** One attempt at one beat. */
export interface Take {
  /**
   * Stable slug, and the streaming id — takes go through the same gated
   * /api/stream/[slug] route as scenes and clips, so this lives in that shared
   * namespace (see lib/content/streamable.ts, which enforces uniqueness).
   *
   * The media filenames are DERIVED from it rather than stored: `takeFile()`
   * and `takeBlobPath()` below. A take with a slug and no file, or a file the
   * data doesn't name, is not a state that can exist.
   */
  slug: string;
  /** Position within its beat, 1-based — the order they were made in. */
  n: number;
  durationSeconds: number;
  /**
   * True for a take that made the finished scene.
   *
   * More than one per beat is normal. In an intercut conversation the edit
   * returns to the same setup repeatedly and pulls a different generation each
   * time — "The Phone Call" uses four of its six Cathy takes.
   */
  used?: boolean;
}

/** A run of attempts at the same moment. */
export interface TakeBeat {
  /** Stable id, unique within the scene. Appears in no URL; safe to rename. */
  id: string;
  /** What this run was trying to get — "He catches her arm". */
  label: string;
  takes: Take[];
}

export interface SceneTakes {
  /** The slug of the finished scene in lib/content/videos.ts. */
  sceneSlug: string;
  beats: TakeBeat[];
}

/** Takes are members-only, always. See the module note. */
export const TAKES_ACCESS: AccessLevel = "premium";

/**
 * Every scene with takes. Generated files are imported explicitly rather than
 * globbed: adding a scene should be a line someone reviewed, and the app
 * should not gain content because a stray folder appeared on disk.
 *
 * Add a scene by sorting its raw clips into beat folders and running
 * scripts/import-takes.sh, which writes lib/content/takes-data/<scene>.ts and
 * prints the import line to add here. A scene with no takes renders nothing
 * rather than an empty shell.
 */
export const takes: SceneTakes[] = [lunaCathyPhoneTakes, tysonColeBarTakes];

/** Proxy basename inside stories/, for the gated stream route. */
export function takeFile(slug: string): string {
  return `${slug}.proxy.mp4`;
}

/**
 * Private path for a take's poster frame — Blob in production, takes-private/
 * on disk locally. Mirrors the members-only stills model: a take's frame must
 * not sit at a permanent public URL any more than the take itself.
 */
export function takePosterPath(sceneSlug: string, slug: string): string {
  return `${sceneSlug}/${slug}.jpg`;
}

export function takesForScene(sceneSlug: string): SceneTakes | undefined {
  return takes.find((t) => t.sceneSlug === sceneSlug);
}

/** Where a take sits, resolved from its slug alone. */
export interface TakeLocation {
  take: Take;
  beat: TakeBeat;
  sceneSlug: string;
}

export function getTake(slug: string): TakeLocation | undefined {
  for (const scene of takes) {
    for (const beat of scene.beats) {
      const take = beat.takes.find((t) => t.slug === slug);
      if (take) return { take, beat, sceneSlug: scene.sceneSlug };
    }
  }
  return undefined;
}

/** Total attempts across a scene — the headline number. */
export function takeCount(scene: SceneTakes): number {
  return scene.beats.reduce((n, beat) => n + beat.takes.length, 0);
}

/** How many of them never made it in. The more interesting number. */
export function unusedCount(scene: SceneTakes): number {
  return scene.beats.reduce(
    (n, beat) => n + beat.takes.filter((t) => !t.used).length,
    0,
  );
}

/** Every take slug, for the cross-kind uniqueness check in streamable.ts. */
export function allTakeSlugs(): string[] {
  return takes.flatMap((s) => s.beats.flatMap((b) => b.takes.map((t) => t.slug)));
}
