/**
 * GENERATED by scripts/import-takes.sh — do not edit.
 *
 * Every attempt at every beat of "josh-luna-wall", in the order they were made,
 * with the one that made the final cut marked. Regenerate by changing the
 * folders under stories/josh-luna-wall/videos/ and re-running:
 *
 *   scripts/import-takes.sh josh-luna-wall
 */

import type { SceneTakes } from "@/lib/content/takes";

export const joshLunaWallTakes: SceneTakes = {
  sceneSlug: "josh-luna-wall",
  beats: [
  {
    id: "he-pins-her-to-the-wall",
    label: "he pins her to the wall",
    takes: [
    {
      slug: "take-josh-luna-wall-he-pins-her-to-the-wall-01",
      n: 1,
      durationSeconds: 10,
    },
    {
      slug: "take-josh-luna-wall-he-pins-her-to-the-wall-02",
      n: 2,
      durationSeconds: 10,
    },
    {
      slug: "take-josh-luna-wall-he-pins-her-to-the-wall-03",
      n: 3,
      durationSeconds: 10,
    },
    {
      slug: "take-josh-luna-wall-he-pins-her-to-the-wall-04",
      n: 4,
      durationSeconds: 10,
    },
    {
      slug: "take-josh-luna-wall-he-pins-her-to-the-wall-05",
      n: 5,
      durationSeconds: 10,
    },
    {
      slug: "take-josh-luna-wall-he-pins-her-to-the-wall-06",
      n: 6,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-he-pins-her-to-the-wall-07",
      n: 7,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-he-pins-her-to-the-wall-08",
      n: 8,
      durationSeconds: 8,
    },
    ],
  },
  {
    id: "holding-her-there",
    label: "holding her there",
    takes: [
    {
      slug: "take-josh-luna-wall-holding-her-there-01",
      n: 1,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-02",
      n: 2,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-03",
      n: 3,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-04",
      n: 4,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-05",
      n: 5,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-06",
      n: 6,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-07",
      n: 7,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-08",
      n: 8,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-09",
      n: 9,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-10",
      n: 10,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-11",
      n: 11,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-12",
      n: 12,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-13",
      n: 13,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-14",
      n: 14,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-15",
      n: 15,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-16",
      n: 16,
      durationSeconds: 10,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-17",
      n: 17,
      durationSeconds: 10,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-18",
      n: 18,
      durationSeconds: 10,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-19",
      n: 19,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-20",
      n: 20,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-21",
      n: 21,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-22",
      n: 22,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-23",
      n: 23,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-24",
      n: 24,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-25",
      n: 25,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-26",
      n: 26,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-27",
      n: 27,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-28",
      n: 28,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-29",
      n: 29,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-30",
      n: 30,
      durationSeconds: 12,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-31",
      n: 31,
      durationSeconds: 12,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-32",
      n: 32,
      durationSeconds: 12,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-33",
      n: 33,
      durationSeconds: 12,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-34",
      n: 34,
      durationSeconds: 12,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-35",
      n: 35,
      durationSeconds: 12,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-36",
      n: 36,
      durationSeconds: 12,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-37",
      n: 37,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-38",
      n: 38,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-39",
      n: 39,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-40",
      n: 40,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-41",
      n: 41,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-42",
      n: 42,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-holding-her-there-43",
      n: 43,
      durationSeconds: 8,
    },
    ],
  },
  {
    id: "his-hand-at-her-throat",
    label: "his hand at her throat",
    takes: [
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-01",
      n: 1,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-02",
      n: 2,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-03",
      n: 3,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-04",
      n: 4,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-05",
      n: 5,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-06",
      n: 6,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-07",
      n: 7,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-08",
      n: 8,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-09",
      n: 9,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-10",
      n: 10,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-11",
      n: 11,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-12",
      n: 12,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-13",
      n: 13,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-14",
      n: 14,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-15",
      n: 15,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-16",
      n: 16,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-17",
      n: 17,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-18",
      n: 18,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-19",
      n: 19,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-20",
      n: 20,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-21",
      n: 21,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-22",
      n: 22,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-23",
      n: 23,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-24",
      n: 24,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-25",
      n: 25,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-his-hand-at-her-throat-26",
      n: 26,
      durationSeconds: 8,
    },
    ],
  },
  {
    id: "he-kisses-her",
    label: "he kisses her",
    takes: [
    {
      slug: "take-josh-luna-wall-he-kisses-her-01",
      n: 1,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-02",
      n: 2,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-03",
      n: 3,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-04",
      n: 4,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-05",
      n: 5,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-06",
      n: 6,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-07",
      n: 7,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-08",
      n: 8,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-09",
      n: 9,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-10",
      n: 10,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-11",
      n: 11,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-12",
      n: 12,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-13",
      n: 13,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-14",
      n: 14,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-15",
      n: 15,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-16",
      n: 16,
      durationSeconds: 9,
    },
    {
      slug: "take-josh-luna-wall-he-kisses-her-17",
      n: 17,
      durationSeconds: 9,
    },
    ],
  },
  {
    id: "what-he-says",
    label: "what he says",
    takes: [
    {
      slug: "take-josh-luna-wall-what-he-says-01",
      n: 1,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-02",
      n: 2,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-03",
      n: 3,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-04",
      n: 4,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-05",
      n: 5,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-06",
      n: 6,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-07",
      n: 7,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-08",
      n: 8,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-09",
      n: 9,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-10",
      n: 10,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-11",
      n: 11,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-12",
      n: 12,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-13",
      n: 13,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-14",
      n: 14,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-15",
      n: 15,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-16",
      n: 16,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-what-he-says-17",
      n: 17,
      durationSeconds: 8,
    },
    ],
  },
  {
    id: "her",
    label: "her",
    takes: [
    {
      slug: "take-josh-luna-wall-her-01",
      n: 1,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-her-02",
      n: 2,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-her-03",
      n: 3,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-her-04",
      n: 4,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-her-05",
      n: 5,
      durationSeconds: 8,
    },
    ],
  },
  {
    id: "the-wide",
    label: "the wide",
    takes: [
    {
      slug: "take-josh-luna-wall-the-wide-01",
      n: 1,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-the-wide-02",
      n: 2,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-the-wide-03",
      n: 3,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-the-wide-04",
      n: 4,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-the-wide-05",
      n: 5,
      durationSeconds: 7,
    },
    {
      slug: "take-josh-luna-wall-the-wide-06",
      n: 6,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-07",
      n: 7,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-08",
      n: 8,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-09",
      n: 9,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-10",
      n: 10,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-11",
      n: 11,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-12",
      n: 12,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-13",
      n: 13,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-14",
      n: 14,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-15",
      n: 15,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-16",
      n: 16,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-17",
      n: 17,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-the-wide-18",
      n: 18,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-the-wide-19",
      n: 19,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-the-wide-20",
      n: 20,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-the-wide-21",
      n: 21,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-the-wide-22",
      n: 22,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-the-wide-23",
      n: 23,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-the-wide-24",
      n: 24,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-the-wide-25",
      n: 25,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-26",
      n: 26,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-27",
      n: 27,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-28",
      n: 28,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-29",
      n: 29,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-30",
      n: 30,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-31",
      n: 31,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-32",
      n: 32,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-33",
      n: 33,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-34",
      n: 34,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-35",
      n: 35,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-36",
      n: 36,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-37",
      n: 37,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-38",
      n: 38,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-39",
      n: 39,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-40",
      n: 40,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-the-wide-41",
      n: 41,
      durationSeconds: 8,
    },
    ],
  },
  {
    id: "at-the-wall",
    label: "at the wall",
    takes: [
    {
      slug: "take-josh-luna-wall-at-the-wall-01",
      n: 1,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-02",
      n: 2,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-03",
      n: 3,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-04",
      n: 4,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-05",
      n: 5,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-06",
      n: 6,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-07",
      n: 7,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-08",
      n: 8,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-09",
      n: 9,
      durationSeconds: 10,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-10",
      n: 10,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-11",
      n: 11,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-12",
      n: 12,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-13",
      n: 13,
      durationSeconds: 10,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-14",
      n: 14,
      durationSeconds: 10,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-15",
      n: 15,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-16",
      n: 16,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-17",
      n: 17,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-18",
      n: 18,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-19",
      n: 19,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-20",
      n: 20,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-21",
      n: 21,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-22",
      n: 22,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-23",
      n: 23,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-24",
      n: 24,
      durationSeconds: 11,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-25",
      n: 25,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-26",
      n: 26,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-27",
      n: 27,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-28",
      n: 28,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-29",
      n: 29,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-30",
      n: 30,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-31",
      n: 31,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-32",
      n: 32,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-33",
      n: 33,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-34",
      n: 34,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-35",
      n: 35,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-36",
      n: 36,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-37",
      n: 37,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-38",
      n: 38,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-39",
      n: 39,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-40",
      n: 40,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-41",
      n: 41,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-42",
      n: 42,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-43",
      n: 43,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-44",
      n: 44,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-45",
      n: 45,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-46",
      n: 46,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-47",
      n: 47,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-48",
      n: 48,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-49",
      n: 49,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-50",
      n: 50,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-51",
      n: 51,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-52",
      n: 52,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-53",
      n: 53,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-54",
      n: 54,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-55",
      n: 55,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-56",
      n: 56,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-57",
      n: 57,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-58",
      n: 58,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-59",
      n: 59,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-60",
      n: 60,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-61",
      n: 61,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-62",
      n: 62,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-63",
      n: 63,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-64",
      n: 64,
      durationSeconds: 8,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-65",
      n: 65,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-66",
      n: 66,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-67",
      n: 67,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-68",
      n: 68,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-69",
      n: 69,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-70",
      n: 70,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-71",
      n: 71,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-72",
      n: 72,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-73",
      n: 73,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-74",
      n: 74,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-75",
      n: 75,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-76",
      n: 76,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-77",
      n: 77,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-78",
      n: 78,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-79",
      n: 79,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-80",
      n: 80,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-81",
      n: 81,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-82",
      n: 82,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-83",
      n: 83,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-84",
      n: 84,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-85",
      n: 85,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-86",
      n: 86,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-87",
      n: 87,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-88",
      n: 88,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-89",
      n: 89,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-90",
      n: 90,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-91",
      n: 91,
      durationSeconds: 6,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-92",
      n: 92,
      durationSeconds: 15,
    },
    {
      slug: "take-josh-luna-wall-at-the-wall-93",
      n: 93,
      durationSeconds: 15,
    },
    ],
  },
  ],
};
