/**
 * GENERATED by scripts/import-takes.sh — do not edit.
 *
 * Every attempt at every beat of "luna-cathy-phone", in the order they were made,
 * with the one that made the final cut marked. Regenerate by changing the
 * folders under stories/luna-mom-phone/videos/ and re-running:
 *
 *   scripts/import-takes.sh luna-cathy-phone luna-mom-phone
 */

import type { SceneTakes } from "@/lib/content/takes";

export const lunaCathyPhoneTakes: SceneTakes = {
  sceneSlug: "luna-cathy-phone",
  beats: [
  {
    id: "she-lets-it-ring",
    label: "she lets it ring",
    takes: [
    {
      slug: "take-luna-cathy-phone-she-lets-it-ring-01",
      n: 1,
      durationSeconds: 4,
    },
    {
      slug: "take-luna-cathy-phone-she-lets-it-ring-02",
      n: 2,
      durationSeconds: 8,
      used: true,
    },
    ],
  },
  {
    id: "picking-up",
    label: "picking up",
    takes: [
    {
      slug: "take-luna-cathy-phone-picking-up-01",
      n: 1,
      durationSeconds: 8,
    },
    {
      slug: "take-luna-cathy-phone-picking-up-02",
      n: 2,
      durationSeconds: 8,
    },
    {
      slug: "take-luna-cathy-phone-picking-up-03",
      n: 3,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-cathy-phone-picking-up-04",
      n: 4,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-cathy-phone-picking-up-05",
      n: 5,
      durationSeconds: 8,
    },
    ],
  },
  {
    id: "her-mother-in-atlanta",
    label: "her mother, in atlanta",
    takes: [
    {
      slug: "take-luna-cathy-phone-her-mother-in-atlanta-01",
      n: 1,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-cathy-phone-her-mother-in-atlanta-02",
      n: 2,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-cathy-phone-her-mother-in-atlanta-03",
      n: 3,
      durationSeconds: 7,
      used: true,
    },
    {
      slug: "take-luna-cathy-phone-her-mother-in-atlanta-04",
      n: 4,
      durationSeconds: 7,
      used: true,
    },
    {
      slug: "take-luna-cathy-phone-her-mother-in-atlanta-05",
      n: 5,
      durationSeconds: 7,
      used: true,
    },
    {
      slug: "take-luna-cathy-phone-her-mother-in-atlanta-06",
      n: 6,
      durationSeconds: 7,
      used: true,
    },
    ],
  },
  {
    id: "listening",
    label: "listening",
    takes: [
    {
      slug: "take-luna-cathy-phone-listening-01",
      n: 1,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-cathy-phone-listening-02",
      n: 2,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-cathy-phone-listening-03",
      n: 3,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-cathy-phone-listening-04",
      n: 4,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-cathy-phone-listening-05",
      n: 5,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-cathy-phone-listening-06",
      n: 6,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-cathy-phone-listening-07",
      n: 7,
      durationSeconds: 8,
    },
    {
      slug: "take-luna-cathy-phone-listening-08",
      n: 8,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-cathy-phone-listening-09",
      n: 9,
      durationSeconds: 6,
      used: true,
    },
    ],
  },
  {
    id: "she-walks-to-the-window",
    label: "she walks to the window",
    takes: [
    {
      slug: "take-luna-cathy-phone-she-walks-to-the-window-01",
      n: 1,
      durationSeconds: 10,
    },
    {
      slug: "take-luna-cathy-phone-she-walks-to-the-window-02",
      n: 2,
      durationSeconds: 10,
    },
    {
      slug: "take-luna-cathy-phone-she-walks-to-the-window-03",
      n: 3,
      durationSeconds: 10,
    },
    {
      slug: "take-luna-cathy-phone-she-walks-to-the-window-04",
      n: 4,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-cathy-phone-she-walks-to-the-window-05",
      n: 5,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-cathy-phone-she-walks-to-the-window-06",
      n: 6,
      durationSeconds: 8,
      used: true,
    },
    {
      slug: "take-luna-cathy-phone-she-walks-to-the-window-07",
      n: 7,
      durationSeconds: 7,
      used: true,
    },
    ],
  },
  ],
};
