/**
 * GENERATED by scripts/import-takes.sh — do not edit.
 *
 * Every attempt at every beat of "luna-tyson-casey-bar", in the order they were made,
 * with the one that made the final cut marked. Regenerate by changing the
 * folders under stories/luna-tyson-casey-bar/videos/ and re-running:
 *
 *   scripts/import-takes.sh luna-tyson-casey-bar
 */

import type { SceneTakes } from "@/lib/content/takes";

export const lunaTysonCaseyBarTakes: SceneTakes = {
  sceneSlug: "luna-tyson-casey-bar",
  beats: [
  {
    id: "luna-on-her-own",
    label: "luna, on her own",
    takes: [
    {
      slug: "take-luna-tyson-casey-bar-luna-on-her-own-01",
      n: 1,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-on-her-own-02",
      n: 2,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-on-her-own-03",
      n: 3,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-on-her-own-04",
      n: 4,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-on-her-own-05",
      n: 5,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-on-her-own-06",
      n: 6,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-on-her-own-07",
      n: 7,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-on-her-own-08",
      n: 8,
      durationSeconds: 5,
    },
    ],
  },
  {
    id: "the-wide",
    label: "the wide",
    takes: [
    {
      slug: "take-luna-tyson-casey-bar-the-wide-01",
      n: 1,
      durationSeconds: 8,
    },
    {
      slug: "take-luna-tyson-casey-bar-the-wide-02",
      n: 2,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-the-wide-03",
      n: 3,
      durationSeconds: 3,
    },
    {
      slug: "take-luna-tyson-casey-bar-the-wide-04",
      n: 4,
      durationSeconds: 8,
    },
    {
      slug: "take-luna-tyson-casey-bar-the-wide-05",
      n: 5,
      durationSeconds: 8,
    },
    ],
  },
  {
    id: "tyson-walks-in-with-her",
    label: "tyson walks in with her",
    takes: [
    {
      slug: "take-luna-tyson-casey-bar-tyson-walks-in-with-her-01",
      n: 1,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-walks-in-with-her-02",
      n: 2,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-walks-in-with-her-03",
      n: 3,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-walks-in-with-her-04",
      n: 4,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-walks-in-with-her-05",
      n: 5,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-walks-in-with-her-06",
      n: 6,
      durationSeconds: 4,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-walks-in-with-her-07",
      n: 7,
      durationSeconds: 8,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-walks-in-with-her-08",
      n: 8,
      durationSeconds: 8,
    },
    ],
  },
  {
    id: "the-three-of-them",
    label: "the three of them",
    takes: [
    {
      slug: "take-luna-tyson-casey-bar-the-three-of-them-01",
      n: 1,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-the-three-of-them-02",
      n: 2,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-the-three-of-them-03",
      n: 3,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-the-three-of-them-04",
      n: 4,
      durationSeconds: 4,
    },
    {
      slug: "take-luna-tyson-casey-bar-the-three-of-them-05",
      n: 5,
      durationSeconds: 4,
    },
    ],
  },
  {
    id: "casey",
    label: "casey",
    takes: [
    {
      slug: "take-luna-tyson-casey-bar-casey-01",
      n: 1,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-02",
      n: 2,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-03",
      n: 3,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-04",
      n: 4,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-05",
      n: 5,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-06",
      n: 6,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-07",
      n: 7,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-08",
      n: 8,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-09",
      n: 9,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-10",
      n: 10,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-11",
      n: 11,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-12",
      n: 12,
      durationSeconds: 4,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-13",
      n: 13,
      durationSeconds: 4,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-14",
      n: 14,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-15",
      n: 15,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-casey-16",
      n: 16,
      durationSeconds: 5,
    },
    ],
  },
  {
    id: "luna-meeting-her",
    label: "luna, meeting her",
    takes: [
    {
      slug: "take-luna-tyson-casey-bar-luna-meeting-her-01",
      n: 1,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-meeting-her-02",
      n: 2,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-meeting-her-03",
      n: 3,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-meeting-her-04",
      n: 4,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-meeting-her-05",
      n: 5,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-meeting-her-06",
      n: 6,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-meeting-her-07",
      n: 7,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-meeting-her-08",
      n: 8,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-meeting-her-09",
      n: 9,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-meeting-her-10",
      n: 10,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-meeting-her-11",
      n: 11,
      durationSeconds: 6,
    },
    ],
  },
  {
    id: "tyson",
    label: "tyson",
    takes: [
    {
      slug: "take-luna-tyson-casey-bar-tyson-01",
      n: 1,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-02",
      n: 2,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-03",
      n: 3,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-04",
      n: 4,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-05",
      n: 5,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-06",
      n: 6,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-07",
      n: 7,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-08",
      n: 8,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-09",
      n: 9,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-10",
      n: 10,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-11",
      n: 11,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-12",
      n: 12,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-13",
      n: 13,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-14",
      n: 14,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-15",
      n: 15,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-16",
      n: 16,
      durationSeconds: 8,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-17",
      n: 17,
      durationSeconds: 8,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-18",
      n: 18,
      durationSeconds: 8,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-19",
      n: 19,
      durationSeconds: 8,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-20",
      n: 20,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-21",
      n: 21,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-22",
      n: 22,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-23",
      n: 23,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-24",
      n: 24,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-25",
      n: 25,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-26",
      n: 26,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-27",
      n: 27,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-28",
      n: 28,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-29",
      n: 29,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-30",
      n: 30,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-31",
      n: 31,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-32",
      n: 32,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-33",
      n: 33,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-34",
      n: 34,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-35",
      n: 35,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-36",
      n: 36,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-37",
      n: 37,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-38",
      n: 38,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-39",
      n: 39,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-tyson-40",
      n: 40,
      durationSeconds: 7,
    },
    ],
  },
  {
    id: "luna-with-tyson",
    label: "luna, with tyson",
    takes: [
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-01",
      n: 1,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-02",
      n: 2,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-03",
      n: 3,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-04",
      n: 4,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-05",
      n: 5,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-06",
      n: 6,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-07",
      n: 7,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-08",
      n: 8,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-09",
      n: 9,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-10",
      n: 10,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-11",
      n: 11,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-12",
      n: 12,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-13",
      n: 13,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-14",
      n: 14,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-15",
      n: 15,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-16",
      n: 16,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-17",
      n: 17,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-18",
      n: 18,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-19",
      n: 19,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-20",
      n: 20,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-21",
      n: 21,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-22",
      n: 22,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-23",
      n: 23,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-24",
      n: 24,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-25",
      n: 25,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-casey-bar-luna-with-tyson-26",
      n: 26,
      durationSeconds: 7,
    },
    ],
  },
  ],
};
