/**
 * GENERATED by scripts/import-takes.sh — do not edit.
 *
 * Every attempt at every beat of "luna-ty-nyc-hotel", in the order they were made,
 * with the one that made the final cut marked. Regenerate by changing the
 * folders under stories/luna-ty-nyc-hotel/videos/ and re-running:
 *
 *   scripts/import-takes.sh luna-ty-nyc-hotel
 */

import type { SceneTakes } from "@/lib/content/takes";

export const lunaTyNycHotelTakes: SceneTakes = {
  sceneSlug: "luna-ty-nyc-hotel",
  beats: [
  {
    id: "she-waits-in-the-lobby",
    label: "she waits in the lobby",
    takes: [
    {
      slug: "take-luna-ty-nyc-hotel-she-waits-in-the-lobby-01",
      n: 1,
      durationSeconds: 15,
      used: true,
    },
    {
      slug: "take-luna-ty-nyc-hotel-she-waits-in-the-lobby-02",
      n: 2,
      durationSeconds: 15,
      used: true,
    },
    {
      slug: "take-luna-ty-nyc-hotel-she-waits-in-the-lobby-03",
      n: 3,
      durationSeconds: 9,
      used: true,
    },
    {
      slug: "take-luna-ty-nyc-hotel-she-waits-in-the-lobby-04",
      n: 4,
      durationSeconds: 9,
      used: true,
    },
    ],
  },
  {
    id: "he-comes-through-the-lobby",
    label: "he comes through the lobby",
    takes: [
    {
      slug: "take-luna-ty-nyc-hotel-he-comes-through-the-lobby-01",
      n: 1,
      durationSeconds: 15,
    },
    {
      slug: "take-luna-ty-nyc-hotel-he-comes-through-the-lobby-02",
      n: 2,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-he-comes-through-the-lobby-03",
      n: 3,
      durationSeconds: 15,
      used: true,
    },
    ],
  },
  {
    id: "they-meet",
    label: "they meet",
    takes: [
    {
      slug: "take-luna-ty-nyc-hotel-they-meet-01",
      n: 1,
      durationSeconds: 11,
    },
    {
      slug: "take-luna-ty-nyc-hotel-they-meet-02",
      n: 2,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-ty-nyc-hotel-they-meet-03",
      n: 3,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-they-meet-04",
      n: 4,
      durationSeconds: 9,
      used: true,
    },
    {
      slug: "take-luna-ty-nyc-hotel-they-meet-05",
      n: 5,
      durationSeconds: 7,
      used: true,
    },
    ],
  },
  {
    id: "upstairs-the-length-of-the-room",
    label: "upstairs, the length of the room",
    takes: [
    {
      slug: "take-luna-ty-nyc-hotel-upstairs-the-length-of-the-room-01",
      n: 1,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-upstairs-the-length-of-the-room-02",
      n: 2,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-upstairs-the-length-of-the-room-03",
      n: 3,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-upstairs-the-length-of-the-room-04",
      n: 4,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-upstairs-the-length-of-the-room-05",
      n: 5,
      durationSeconds: 9,
    },
    ],
  },
  {
    id: "at-the-bar",
    label: "at the bar",
    takes: [
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-01",
      n: 1,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-02",
      n: 2,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-03",
      n: 3,
      durationSeconds: 15,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-04",
      n: 4,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-05",
      n: 5,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-06",
      n: 6,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-07",
      n: 7,
      durationSeconds: 13,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-08",
      n: 8,
      durationSeconds: 13,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-09",
      n: 9,
      durationSeconds: 13,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-10",
      n: 10,
      durationSeconds: 11,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-11",
      n: 11,
      durationSeconds: 11,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-12",
      n: 12,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-13",
      n: 13,
      durationSeconds: 13,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-14",
      n: 14,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-15",
      n: 15,
      durationSeconds: 8,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-16",
      n: 16,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-17",
      n: 17,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-18",
      n: 18,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-at-the-bar-19",
      n: 19,
      durationSeconds: 9,
    },
    ],
  },
  {
    id: "close",
    label: "close",
    takes: [
    {
      slug: "take-luna-ty-nyc-hotel-close-01",
      n: 1,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-02",
      n: 2,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-03",
      n: 3,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-04",
      n: 4,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-05",
      n: 5,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-06",
      n: 6,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-07",
      n: 7,
      durationSeconds: 14,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-08",
      n: 8,
      durationSeconds: 15,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-09",
      n: 9,
      durationSeconds: 10,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-10",
      n: 10,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-11",
      n: 11,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-12",
      n: 12,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-13",
      n: 13,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-14",
      n: 14,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-15",
      n: 15,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-16",
      n: 16,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-17",
      n: 17,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-18",
      n: 18,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-19",
      n: 19,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-20",
      n: 20,
      durationSeconds: 9,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-21",
      n: 21,
      durationSeconds: 12,
    },
    {
      slug: "take-luna-ty-nyc-hotel-close-22",
      n: 22,
      durationSeconds: 12,
    },
    ],
  },
  {
    id: "he-picks-her-up",
    label: "he picks her up",
    takes: [
    {
      slug: "take-luna-ty-nyc-hotel-he-picks-her-up-01",
      n: 1,
      durationSeconds: 11,
    },
    {
      slug: "take-luna-ty-nyc-hotel-he-picks-her-up-02",
      n: 2,
      durationSeconds: 11,
    },
    {
      slug: "take-luna-ty-nyc-hotel-he-picks-her-up-03",
      n: 3,
      durationSeconds: 11,
    },
    {
      slug: "take-luna-ty-nyc-hotel-he-picks-her-up-04",
      n: 4,
      durationSeconds: 13,
    },
    ],
  },
  ],
};
