/**
 * GENERATED by scripts/import-takes.sh — do not edit.
 *
 * Every attempt at every beat of "luna-tyson-gingerale", in the order they were made,
 * with the one that made the final cut marked. Regenerate by changing the
 * folders under stories/luna-tyson-gingerale/videos/ and re-running:
 *
 *   scripts/import-takes.sh luna-tyson-gingerale
 */

import type { SceneTakes } from "@/lib/content/takes";

export const lunaTysonGingeraleTakes: SceneTakes = {
  sceneSlug: "luna-tyson-gingerale",
  beats: [
  {
    id: "she-opens-the-fridge",
    label: "she opens the fridge",
    takes: [
    {
      slug: "take-luna-tyson-gingerale-she-opens-the-fridge-01",
      n: 1,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-she-opens-the-fridge-02",
      n: 2,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-she-opens-the-fridge-03",
      n: 3,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-she-opens-the-fridge-04",
      n: 4,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-she-opens-the-fridge-05",
      n: 5,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-she-opens-the-fridge-06",
      n: 6,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-she-opens-the-fridge-07",
      n: 7,
      durationSeconds: 8,
    },
    {
      slug: "take-luna-tyson-gingerale-she-opens-the-fridge-08",
      n: 8,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-she-opens-the-fridge-09",
      n: 9,
      durationSeconds: 7,
    },
    ],
  },
  {
    id: "he-comes-in",
    label: "he comes in",
    takes: [
    {
      slug: "take-luna-tyson-gingerale-he-comes-in-01",
      n: 1,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-he-comes-in-02",
      n: 2,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-he-comes-in-03",
      n: 3,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-gingerale-he-comes-in-04",
      n: 4,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-gingerale-he-comes-in-05",
      n: 5,
      durationSeconds: 5,
    },
    {
      slug: "take-luna-tyson-gingerale-he-comes-in-06",
      n: 6,
      durationSeconds: 5,
    },
    ],
  },
  {
    id: "the-two-of-them",
    label: "the two of them",
    takes: [
    {
      slug: "take-luna-tyson-gingerale-the-two-of-them-01",
      n: 1,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-the-two-of-them-02",
      n: 2,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-the-two-of-them-03",
      n: 3,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-the-two-of-them-04",
      n: 4,
      durationSeconds: 10,
    },
    {
      slug: "take-luna-tyson-gingerale-the-two-of-them-05",
      n: 5,
      durationSeconds: 10,
    },
    {
      slug: "take-luna-tyson-gingerale-the-two-of-them-06",
      n: 6,
      durationSeconds: 10,
    },
    {
      slug: "take-luna-tyson-gingerale-the-two-of-them-07",
      n: 7,
      durationSeconds: 10,
    },
    {
      slug: "take-luna-tyson-gingerale-the-two-of-them-08",
      n: 8,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-gingerale-the-two-of-them-09",
      n: 9,
      durationSeconds: 7,
    },
    ],
  },
  {
    id: "her-over-his-shoulder",
    label: "her, over his shoulder",
    takes: [
    {
      slug: "take-luna-tyson-gingerale-her-over-his-shoulder-01",
      n: 1,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-her-over-his-shoulder-02",
      n: 2,
      durationSeconds: 8,
    },
    {
      slug: "take-luna-tyson-gingerale-her-over-his-shoulder-03",
      n: 3,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-her-over-his-shoulder-04",
      n: 4,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-her-over-his-shoulder-05",
      n: 5,
      durationSeconds: 7,
    },
    {
      slug: "take-luna-tyson-gingerale-her-over-his-shoulder-06",
      n: 6,
      durationSeconds: 7,
    },
    ],
  },
  {
    id: "she-gives-up",
    label: "she gives up",
    takes: [
    {
      slug: "take-luna-tyson-gingerale-she-gives-up-01",
      n: 1,
      durationSeconds: 6,
    },
    {
      slug: "take-luna-tyson-gingerale-she-gives-up-02",
      n: 2,
      durationSeconds: 12,
    },
    {
      slug: "take-luna-tyson-gingerale-she-gives-up-03",
      n: 3,
      durationSeconds: 12,
    },
    ],
  },
  ],
};
