/**
 * GENERATED by scripts/import-takes.sh — do not edit.
 *
 * Every attempt at every beat of "tyson-cole-bar", in the order they were made,
 * with the one that made the final cut marked. Regenerate by changing the
 * folders under stories/tyson-cole-bar/videos/ and re-running:
 *
 *   scripts/import-takes.sh tyson-cole-bar
 */

import type { SceneTakes } from "@/lib/content/takes";

export const tysonColeBarTakes: SceneTakes = {
  sceneSlug: "tyson-cole-bar",
  beats: [
  {
    id: "he-walks-in",
    label: "he walks in",
    takes: [
    {
      slug: "take-tyson-cole-bar-he-walks-in-01",
      n: 1,
      durationSeconds: 6,
      used: true,
    },
    ],
  },
  {
    id: "at-the-bar",
    label: "at the bar",
    takes: [
    {
      slug: "take-tyson-cole-bar-at-the-bar-01",
      n: 1,
      durationSeconds: 6,
    },
    {
      slug: "take-tyson-cole-bar-at-the-bar-02",
      n: 2,
      durationSeconds: 7,
    },
    {
      slug: "take-tyson-cole-bar-at-the-bar-03",
      n: 3,
      durationSeconds: 8,
    },
    {
      slug: "take-tyson-cole-bar-at-the-bar-04",
      n: 4,
      durationSeconds: 7,
    },
    {
      slug: "take-tyson-cole-bar-at-the-bar-05",
      n: 5,
      durationSeconds: 7,
      used: true,
    },
    ],
  },
  {
    id: "cole-behind-the-bar",
    label: "cole, behind the bar",
    takes: [
    {
      slug: "take-tyson-cole-bar-cole-behind-the-bar-01",
      n: 1,
      durationSeconds: 8,
    },
    {
      slug: "take-tyson-cole-bar-cole-behind-the-bar-02",
      n: 2,
      durationSeconds: 8,
    },
    {
      slug: "take-tyson-cole-bar-cole-behind-the-bar-03",
      n: 3,
      durationSeconds: 6,
    },
    {
      slug: "take-tyson-cole-bar-cole-behind-the-bar-04",
      n: 4,
      durationSeconds: 8,
    },
    {
      slug: "take-tyson-cole-bar-cole-behind-the-bar-05",
      n: 5,
      durationSeconds: 7,
    },
    {
      slug: "take-tyson-cole-bar-cole-behind-the-bar-06",
      n: 6,
      durationSeconds: 7,
      used: true,
    },
    ],
  },
  ],
};
