import type { Metadata } from "next";

/**
 * One place that builds a page's share card.
 *
 * THE BUG THIS EXISTS TO FIX. Pages were setting `title` and `description` and
 * nothing else. Next merges metadata by KEY, not by meaning — so a page that
 * sets `title` but no `openGraph.title` keeps the ROOT openGraph block intact,
 * and every link anyone posted came out identical: "Luna Vale — An explorable
 * cinematic universe of original stories", whether it pointed at the notebook,
 * a journal entry or the membership page. The tab title was right and the
 * shared card, which is the one strangers actually see, was not.
 *
 * So openGraph and twitter are never written by hand at the page level. They
 * are derived here from the same title and description the page already
 * declares, which makes them impossible to forget and impossible to disagree
 * with each other.
 *
 * IMAGES ARE PUBLIC-ONLY, and that is a hard rule rather than a convention. A
 * share card is fetched by crawlers with no session — Facebook, Instagram,
 * iMessage, Slack — so anything named here is, in effect, published. Posters
 * in /public are safe by construction: lib/content/videos.ts guarantees a
 * `poster` always belongs to the PUBLIC cut. Members-only stills go through the
 * gated /api/still route and must never be passed to this function; they would
 * either leak the material the membership sells or render as a broken card,
 * and the first one is much worse than the second.
 */

/** The site-wide fallback card, generated by app/opengraph-image.tsx. */
const DEFAULT_IMAGE = "/opengraph-image";

export interface PageMetaInput {
  /** Page title, without the "· Luna Vale" suffix — the template adds it. */
  title: string;
  description: string;
  /** Absolute path, for the canonical URL. Resolved against metadataBase. */
  path: string;
  /**
   * A PUBLIC image path for the card, e.g. a scene poster. Omit for the
   * site default. Never pass a gated or members-only image.
   */
  image?: string;
  /** True for pages that shouldn't be indexed (account, admin, auth). */
  noIndex?: boolean;
}

export function pageMetadata({
  title,
  description,
  path,
  image,
  noIndex = false,
}: PageMetaInput): Metadata {
  // The template in app/layout.tsx appends "· Luna Vale" to <title>, but it
  // does NOT apply to Open Graph — so the site name is added explicitly here.
  // Without it a shared card reads just "The wrong cupboards", with nothing
  // saying what it belongs to.
  const cardTitle = `${title} · Luna Vale`;
  const images = [{ url: image ?? DEFAULT_IMAGE }];

  return {
    title,
    description,
    alternates: { canonical: path },
    ...(noIndex ? { robots: { index: false, follow: false } } : {}),
    openGraph: {
      title: cardTitle,
      description,
      url: path,
      siteName: "Luna Vale",
      type: "website",
      images,
    },
    twitter: {
      card: "summary_large_image",
      title: cardTitle,
      description,
      images,
    },
  };
}

/**
 * Trim prose to something a share card can actually show.
 *
 * Cards are clipped at roughly 160-200 characters depending on the client, and
 * a description cut mid-word by the platform looks worse than one cut cleanly
 * here. Breaks on a word boundary and adds an ellipsis only when it actually
 * truncated.
 */
export function cardDescription(text: string, limit = 160): string {
  const clean = text.replace(/\s+/g, " ").trim();
  if (clean.length <= limit) return clean;
  const cut = clean.slice(0, limit);
  const lastSpace = cut.lastIndexOf(" ");
  return `${cut.slice(0, lastSpace > 0 ? lastSpace : limit).replace(/[,;:.—-]$/, "")}…`;
}
